title: Dale Rabena
description: Computer Programmer @ Mariano Marcos State University
show_downloads: false
google_analytics: UA-105746837-1
theme: jekyll-theme-cayman

facebook_url: http://www.facebook.com/dale.rabena
github_url: http://github.com/dalerabena
linkedin_url: http://www.linkedin.com/in/dalerabena
